version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
    - 10.2.0
    - 10.3.0
    - 10.4.0
  - dependency-name: i18next
    versions:
    - 19.8.8
    - 19.8.9
    - 19.9.0
    - 19.9.1
    - 20.0.0
    - 20.1.0
    - 20.2.0
  - dependency-name: ember-cli-babel
    versions:
    - 7.26.0
    - 7.26.1
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.4.0
    - 5.6.1
    - 5.6.2
    - 5.6.3
    - 5.6.4
    - 5.6.5
    - 5.7.0
  - dependency-name: ember-template-lint
    versions:
    - 2.19.0
    - 2.20.0
    - 2.21.0
    - 3.0.0
    - 3.0.1
    - 3.1.1
  - dependency-name: ember-qunit
    versions:
    - 5.1.3
  - dependency-name: ember-cli
    versions:
    - 3.25.0
    - 3.25.1
  - dependency-name: eslint
    versions:
    - 7.21.0
  - dependency-name: ember-source
    versions:
    - 3.25.1
