---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - $HOME/.npm

env:
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-2.12

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - npm config set spin false
  - npm install -g phantomjs-prebuilt
  - phantomjs --version

install:
  - npm install

script:
  - ember try:one $EMBER_TRY_SCENARIO
