name: CI

on:
  push:
    branches:
      - master
      - "v*"
  pull_request: {}

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          # Ember recommends testing addons with the same minimum supported node version as Ember CLI
          node-version: 14.x

      - name: get yarn cache dir
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-lint-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn install

      - name: lint
        run: yarn lint

  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-suite:
          - test:one ember-lts-3.28
          - test:one ember-lts-4.4
          - test:one ember-lts-4.8
          - test:one ember-release
          # - test:one ember-beta

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          # Ember recommends testing addons with the same minimum supported node version as Ember CLI
          node-version: 14.x

      - name: get yarn cache dir
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-test-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn install

      - name: tests
        run: yarn ${{ matrix.test-suite }}

  extra-tests:
    name: Tests (Floating Dependenies)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          # Ember recommends testing addons with the same minimum supported node version as Ember CLI
          node-version: 14.x

      - name: get yarn cache dir
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-test-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn install --no-lockfile

      - name: tests
        run: yarn test:ember
        continue-on-error: true
